2025-08-18 19:10:47.066 | DEBUG    | ttnn:<module>:83 - Initial ttnn.CONFIG:
Config{cache_path=/home/ubuntu/.cache/ttnn,model_cache_path=/home/ubuntu/.cache/ttnn/models,tmp_dir=/tmp/ttnn,enable_model_cache=false,enable_fast_runtime_mode=true,throw_exception_on_fallback=false,enable_logging=false,enable_graph_report=false,enable_detailed_buffer_report=false,enable_detailed_tensor_report=false,enable_comparison_mode=false,comparison_mode_should_raise_exception=false,comparison_mode_pcc=0.9999,root_report_path=generated/ttnn/reports,report_name=std::nullopt,std::nullopt}
2025-08-18 19:10:47.171 | info     |   SiliconDriver | Opened PCI device 0; KMD version: 2.3.0; API: 2; IOMMU: disabled (pci_device.cpp:197)
2025-08-18 19:10:47.183 | info     |          Device | Opening user mode device driver (tt_cluster.cpp:192)
2025-08-18 19:10:47.183 | info     |   SiliconDriver | Opened PCI device 0; KMD version: 2.3.0; API: 2; IOMMU: disabled (pci_device.cpp:197)
2025-08-18 19:10:47.195 | info     |   SiliconDriver | Opened PCI device 0; KMD version: 2.3.0; API: 2; IOMMU: disabled (pci_device.cpp:197)
2025-08-18 19:10:47.207 | info     |   SiliconDriver | Harvesting mask for chip 0 is 0x18 (NOC0: 0x18, simulated harvesting mask: 0x0). (cluster.cpp:295)
2025-08-18 19:10:47.224 | info     |   SiliconDriver | Opened PCI device 0; KMD version: 2.3.0; API: 2; IOMMU: disabled (pci_device.cpp:197)
2025-08-18 19:10:47.240 | warning  |   SiliconDriver | init_detect_tt_device_numanodes(): Could not determine NumaNodeSet for TT device (physical_device_id: 0 pci_bus_id: 0000:04:00.0) (cpuset_lib.cpp:578)
2025-08-18 19:10:47.240 | warning  |   SiliconDriver | Could not find NumaNodeSet for TT Device (physical_device_id: 0 pci_bus_id: 0000:04:00.0) (cpuset_lib.cpp:182)
2025-08-18 19:10:47.241 | warning  |   SiliconDriver | bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind. (cpuset_lib.cpp:463)
2025-08-18 19:10:47.241 | warning  |   SiliconDriver | ---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 0). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893). (sysmem_manager.cpp:198)
2025-08-18 19:10:47.241 | warning  |   SiliconDriver | bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind. (cpuset_lib.cpp:463)
2025-08-18 19:10:47.241 | warning  |   SiliconDriver | ---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 1). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893). (sysmem_manager.cpp:198)
2025-08-18 19:10:47.241 | info     |   SiliconDriver | Harvesting mask for chip 1 is 0x82 (NOC0: 0x82, simulated harvesting mask: 0x0). (cluster.cpp:295)
2025-08-18 19:10:47.259 | info     |   SiliconDriver | Opening local chip ids/pci ids: {0}/[0] and remote chip ids {1} (cluster.cpp:157)
2025-08-18 19:10:47.260 | info     |   SiliconDriver | All devices in cluster running firmware version: 18.5.0 (cluster.cpp:138)
2025-08-18 19:10:47.260 | info     |   SiliconDriver | Software version 6.0.0, Ethernet FW version 6.15.0 (Device 0) (cluster.cpp:935)
2025-08-18 19:10:47.261 | info     |   SiliconDriver | Software version 6.0.0, Ethernet FW version 6.15.0 (Device 1) (cluster.cpp:935)
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.2.2, pluggy-1.6.0 -- /home/ubuntu/work/yolov12-high-res-tests/tt-metal/python_env/bin/python
cachedir: .pytest_cache
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ubuntu/work/yolov12-high-res-tests/tt-metal, configfile: pytest.ini
plugins: timeout-2.2.0, anyio-4.10.0, github-actions-annotate-failures-0.3.0, dash-2.15.0, xdist-3.6.1, benchmark-4.0.0, split-0.8.2
timeout: 300.0s
timeout method: signal
timeout func_only: False
collecting ... collected 3 items

ssinghal/tests/test_copy.py::test_copy[input_shape0] FAILED
ssinghal/tests/test_copy.py::test_copy[input_shape1] 2025-08-18 19:10:50.344 | warning  |          Always | Closing and re-initializing MetalContext with same parameters due to force_reinit flag. (metal_context.cpp:77)
FAILED
ssinghal/tests/test_copy.py::test_copy[input_shape2] 2025-08-18 19:10:50.439 | warning  |          Always | Closing and re-initializing MetalContext with same parameters due to force_reinit flag. (metal_context.cpp:77)
FAILED

=================================== FAILURES ===================================
___________________________ test_copy[input_shape0] ____________________________
ssinghal/tests/test_copy.py:46: in test_copy
    raise e
ssinghal/tests/test_copy.py:29: in test_copy
    torch_reference = torch.copy_(torch_input1, torch_input2)
python_env/lib/python3.10/site-packages/torch/__init__.py:2688: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
E   AttributeError: module 'torch' has no attribute 'copy_'
___________________________ test_copy[input_shape1] ____________________________
ssinghal/tests/test_copy.py:46: in test_copy
    raise e
ssinghal/tests/test_copy.py:29: in test_copy
    torch_reference = torch.copy_(torch_input1, torch_input2)
python_env/lib/python3.10/site-packages/torch/__init__.py:2688: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
E   AttributeError: module 'torch' has no attribute 'copy_'
___________________________ test_copy[input_shape2] ____________________________
ssinghal/tests/test_copy.py:46: in test_copy
    raise e
ssinghal/tests/test_copy.py:29: in test_copy
    torch_reference = torch.copy_(torch_input1, torch_input2)
python_env/lib/python3.10/site-packages/torch/__init__.py:2688: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
E   AttributeError: module 'torch' has no attribute 'copy_'
- generated xml file: /home/ubuntu/work/yolov12-high-res-tests/tt-metal/generated/test_reports/most_recent_tests.xml -
============================== slowest durations ===============================
2.11s setup    ssinghal/tests/test_copy.py::test_copy[input_shape0]
0.55s call     ssinghal/tests/test_copy.py::test_copy[input_shape0]
0.06s setup    ssinghal/tests/test_copy.py::test_copy[input_shape1]
0.06s setup    ssinghal/tests/test_copy.py::test_copy[input_shape2]
0.00s call     ssinghal/tests/test_copy.py::test_copy[input_shape1]
0.00s teardown ssinghal/tests/test_copy.py::test_copy[input_shape0]
0.00s call     ssinghal/tests/test_copy.py::test_copy[input_shape2]
0.00s teardown ssinghal/tests/test_copy.py::test_copy[input_shape1]
0.00s teardown ssinghal/tests/test_copy.py::test_copy[input_shape2]
=========================== short test summary info ============================
FAILED ssinghal/tests/test_copy.py::test_copy[input_shape0] - AttributeError:...
FAILED ssinghal/tests/test_copy.py::test_copy[input_shape1] - AttributeError:...
FAILED ssinghal/tests/test_copy.py::test_copy[input_shape2] - AttributeError:...
============================== 3 failed in 3.22s ===============================
2025-08-18 19:10:51.192 | info     |          Device | Closing user mode device drivers (tt_cluster.cpp:406)
